spring:
  config:
    import: optional:classpath:application-admins.yml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${DB_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${DB_SHOW_SQL:false}


logging:
  level:
    com.projetomta: INFO
    org.hibernate.SQL: ${DB_LOG_SQL:WARN}

app:
  seed:
    admin-email: ${SEED_ADMIN_EMAIL:admin@mta.local}
    admin-password: ${SEED_ADMIN_PASSWORD:admin123}

